spring:
  application:
    name: home_manager
  data:
    mongodb:
      uri: ${MONGO_URI}

server:
  servlet:
    context-path: /homemanager

application:
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      expiration: ${ACCESS_TOKEN_EXP}
      refresh-token:
        expiration: ${REFRESH_TOKEN_EXP}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    config:
      init:
        enableAuthentication: true

logging:
  level:
    root: INFO
    com.example.homemanager: INFO  # o INFO mínimo
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

