version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo-docker
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27018:27018
    volumes:
      - mongo_data:/data/db
      - ./backup:/docker-entrypoint-initdb.d/backup # Volumen para respaldos o datos pre-cargados (opcional)

volumes:
  mongo_data:
    driver: local
